Add new rpc for posts and reactions pallets
dappforce/subsocial-node pull request #114
Opened 2021-05-11 09:51 UTC by olehmell

2021-05-14 15:46 UTC, F3Joule requested changes

2021-05-14 15:46 UTC, F3Joule commented on pallets/posts/rpc/runtime-api/src/lib.rs
> +use pallet_utils::{PostId, SpaceId };
```suggestion
use pallet_utils::{PostId, SpaceId};
```

2021-05-14 15:46 UTC, F3Joule commented on pallets/posts/src/rpc.rs
> +pub enum ExtFilter {
Maybe rename to more descriptive name? e.g. `PostExtensionFilter`

2021-05-14 15:46 UTC, F3Joule commented on pallets/posts/rpc/runtime-api/src/lib.rs
> +        fn get_public_posts(ext_filter: Vec<ExtFilter>, offset: u64, limit: u16) -> Vec<FlatPost<AccountId, BlockNumber>>;
```suggestion
        fn get_public_posts(ext_filters: Vec<ExtFilter>, offset: u64, limit: u16) -> Vec<FlatPost<AccountId, BlockNumber>>;
```

2021-05-14 15:46 UTC, F3Joule commented on pallets/posts/rpc/src/lib.rs
> +        ext_filter: Vec<ExtFilter>,
```suggestion
        ext_filters: Vec<ExtFilter>,
```

2021-05-14 15:46 UTC, F3Joule commented on pallets/posts/rpc/src/lib.rs
> +        ext_filter: Vec<ExtFilter>,
```suggestion
        ext_filters: Vec<ExtFilter>,
```

2021-05-14 15:46 UTC, F3Joule commented on pallets/posts/src/rpc.rs
> +        ext_filter: Vec<ExtFilter>,
```suggestion
        ext_filters: Vec<ExtFilter>,
```

2021-05-14 15:46 UTC, F3Joule commented on runtime/src/lib.rs
> +		fn get_public_posts(ext_filter: Vec<ExtFilter>, offset: u64, limit: u16) -> Vec<FlatPost<AccountId, BlockNumber>> {
```suggestion
		fn get_public_posts(ext_filters: Vec<ExtFilter>, offset: u64, limit: u16) -> Vec<FlatPost<AccountId, BlockNumber>> {
```

2021-05-14 15:46 UTC, F3Joule commented on pallets/posts/rpc/src/lib.rs
> +    #[rpc(name = "posts_getRepliesByParentId")]
```suggestion
    #[rpc(name = "posts_getRepliesByParentIds")]
```

2021-05-14 15:46 UTC, F3Joule commented on pallets/posts/rpc/src/lib.rs
> +    ) -> Result<BTreeMap<PostId,Vec<FlatPost<AccountId, BlockNumber>>>>;
```suggestion
    ) -> Result<BTreeMap<PostId, Vec<FlatPost<AccountId, BlockNumber>>>>;
```

2021-05-14 15:46 UTC, F3Joule commented on pallets/posts/rpc/src/lib.rs
> +    ) -> Result<BTreeMap<PostId,Vec<FlatPost<AccountId, BlockNumber>>>> {
```suggestion
    ) -> Result<BTreeMap<PostId, Vec<FlatPost<AccountId, BlockNumber>>>> {
```

2021-05-14 15:46 UTC, F3Joule commented on pallets/posts/src/rpc.rs
> +use sp_std::collections::{ btree_map::BTreeMap, btree_set::BTreeSet };
```suggestion
use sp_std::collections::{btree_map::BTreeMap, btree_set::BTreeSet};
```

2021-05-15 16:26 UTC, F3Joule requested changes

2021-05-15 16:26 UTC, F3Joule commented on pallets/reactions/src/rpc.rs
> +        reactor: T::AccountId,
So responder or reactor?

2021-05-18 11:49 UTC, siman requested changes

2021-05-18 11:50 UTC, merged