Zee rate limiter
dappforce/subsocial-node pull request #151
Opened 2021-11-02 12:49 UTC by zeeshanakram3

- [x]  Updated Trust Pallet and Rate Limiting pallet to Substrate v3.0.0
- [x] Implemented sliding window rate limiting algorithm for free calls.
- [ ] Adds tests for Rate Limiter and Trust pallets. 

#131

2021-11-15 12:23 UTC, F3Joule reviewed
Needs extra check of a rate-limiter design.

2021-11-15 12:23 UTC, F3Joule commented on pallets/trust/src/mock.rs
> +	pub const SS58Prefix: u8 = 28;
```suggestion
```

2021-11-15 12:23 UTC, F3Joule commented on runtime/Cargo.toml
> +]
extra formatting

2021-11-15 12:23 UTC, F3Joule commented on runtime/src/lib.rs
> +use sp_std::{prelude::*, collections::btree_map::BTreeMap};
extra formatting

2021-11-15 12:23 UTC, F3Joule commented on runtime/src/lib.rs
> +use sp_runtime::traits::{BlakeTwo256, Block as BlockT, NumberFor, AccountIdLookup};
extra formatting

2021-11-15 12:23 UTC, F3Joule commented on runtime/src/lib.rs
> +	limits::{BlockWeights, BlockLength},
extra formatting

2021-11-15 12:23 UTC, F3Joule commented on runtime/src/lib.rs
> -};
extra formatting

2021-11-15 12:23 UTC, F3Joule commented on runtime/src/lib.rs
> +	type IsContentBlocked = ();
leave the comments here

2021-11-15 12:23 UTC, F3Joule commented on runtime/src/lib.rs
> +	type IsPostBlocked = ();
leave a comment here

2021-11-15 12:23 UTC, F3Joule commented on runtime/src/lib.rs
> +	type IsContentBlocked = ();
leave the comments here

2021-11-15 12:23 UTC, F3Joule commented on runtime/src/lib.rs
> +			matches!(c, Call::Balances(pallet_balances::Call::force_transfer(..)));
extra formatting

2021-11-23 18:26 UTC, zeeshanakram3 commented on pallets/df-integration-tests/Cargo.toml
> +]
Done

2021-11-23 19:41 UTC, zeeshanakram3 commented on pallets/df-integration-tests/Cargo.toml
> +]
Done

2021-11-23 19:42 UTC, zeeshanakram3 commented on pallets/df-integration-tests/Cargo.toml
> +] }
Done

2021-11-23 19:43 UTC, zeeshanakram3 commented on pallets/df-integration-tests/src/lib.rs
> +		traits::Filter,
Done

2021-11-23 19:44 UTC, zeeshanakram3 commented on pallets/df-integration-tests/src/lib.rs
> +    use pallet_spaces::{Error as SpacesError, Space, SpaceById, SpaceUpdate, SpacesSettings};
Done

2021-11-23 19:44 UTC, zeeshanakram3 commented on pallets/df-integration-tests/src/lib.rs
> +        type WeightInfo = SubstrateWeight<TestRuntime>;
Done

2021-11-23 19:45 UTC, zeeshanakram3 commented on pallets/df-integration-tests/src/lib.rs
> +    pub(crate) const MINUTES: BlockNumber = 60 as BlockNumber;
Done

2021-11-23 19:45 UTC, zeeshanakram3 commented on pallets/df-integration-tests/src/lib.rs
> +            let mut ext = Self::build();
Done

2021-11-23 19:45 UTC, zeeshanakram3 commented on pallets/df-integration-tests/src/lib.rs
> +                Self::add_default_space();
Done

2021-11-23 19:46 UTC, zeeshanakram3 commented on pallets/df-integration-tests/src/lib.rs
> +            let mut ext = Self::build();
Done

2021-11-23 19:46 UTC, zeeshanakram3 commented on pallets/df-integration-tests/src/lib.rs
> +                Self::add_default_space();
Done

2021-11-23 19:46 UTC, zeeshanakram3 commented on pallets/trust/src/mock.rs
> +	pub const SS58Prefix: u8 = 28;
Done

2021-11-23 19:47 UTC, zeeshanakram3 commented on runtime/Cargo.toml
> +]
Done

2021-11-23 19:47 UTC, zeeshanakram3 commented on runtime/src/lib.rs
> +use sp_std::{prelude::*, collections::btree_map::BTreeMap};
Done

2021-11-23 19:55 UTC, zeeshanakram3 commented on runtime/src/lib.rs
> +			matches!(c, Call::Balances(pallet_balances::Call::force_transfer(..)));
Done

2021-11-23 19:56 UTC, zeeshanakram3 commented on runtime/src/lib.rs
> +	type IsContentBlocked = ();
Done

2021-11-23 19:56 UTC, zeeshanakram3 commented on runtime/src/lib.rs
> +	type IsPostBlocked = ();
Done

2021-11-23 19:56 UTC, zeeshanakram3 commented on runtime/src/lib.rs
> +	type IsContentBlocked = ();
Done

2021-11-24 09:06 UTC, zeeshanakram3 commented on pallets/df-integration-tests/src/lib.rs
> +        //   }
Will be used for testing free calls with multiple window sizes.

2021-11-29 14:22 UTC, F3Joule commented on pallets/rate-limiter/src/lib.rs
> +        // TODO should this be public or private
This should be public.

2021-11-29 15:20 UTC, F3Joule requested changes

2021-11-29 15:20 UTC, F3Joule commented on pallets/trust/src/lib.rs
> +pub use weights::*;
```suggestion
pub use weights::WeightInfo;
```

2021-11-29 15:22 UTC, F3Joule commented on pallets/rate-limiter/src/lib.rs
> +                stats.current_window_consumed_permits.into();
Consider splitting into more primitive calculations. Furthermore, `Saturating` is good to use here.

2022-03-16 09:30 UTC, closed without merging