Merge required branches before Substrate 2.0.0 update
dappforce/subsocial-node pull request #96
Opened 2021-02-22 18:52 UTC by F3Joule

2021-03-08 15:57 UTC, F3Joule commented on pallets/permissions/src/default_permissions.rs
> +#[allow(unused_imports)]
```suggestion
```

2021-03-08 15:57 UTC, F3Joule commented on pallets/permissions/src/default_permissions.rs
> +}
```suggestion
}

```

2021-03-08 15:57 UTC, F3Joule commented on pallets/posts/src/functions.rs
> +        // TODO check whether post and its content are not blocked within a new space
There should be a way to set up checks here without implementing pallet-moderation into the Runtime

2021-03-08 15:57 UTC, F3Joule commented on pallets/session-keys/Cargo.toml
> +version = '0.4.0'
```suggestion
```

2021-03-08 15:57 UTC, F3Joule commented on pallets/session-keys/Cargo.toml
> +version = '0.4.0'
```suggestion
```

2021-03-08 15:57 UTC, F3Joule commented on pallets/session-keys/Cargo.toml
> +version = '0.4.0'
```suggestion
```

2021-03-08 15:57 UTC, F3Joule commented on runtime/Cargo.toml
> +#    'session-keys/std',
```suggestion
#    'pallet-session-keys/std',
```

2021-03-21 21:43 UTC, siman commented
4 failures in df-integration-tests:

```
failures:

---- tests::move_hidden_post_should_fail_cannot_move_comment stdout ----
thread 'tests::move_hidden_post_should_fail_cannot_move_comment' panicked at 'assertion failed: `(left == right)`
  left: `Err(DispatchError::Module { index: 0, error: 0, message: Some("AccountIsBlocked") })`,
 right: `Err(DispatchError::Module { index: 0, error: 10, message: Some("CannotUpdateSpaceIdOnComment") })`', pallets/df-integration-tests/src/lib.rs:2010:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::move_hidden_post_should_fail_no_permission_to_create_post stdout ----
thread 'tests::move_hidden_post_should_fail_no_permission_to_create_post' panicked at 'assertion failed: `(left == right)`
  left: `Err(DispatchError::Module { index: 0, error: 0, message: Some("AccountIsBlocked") })`,
 right: `Err(DispatchError::Module { index: 0, error: 14, message: Some("NoPermissionToCreatePosts") })`', pallets/df-integration-tests/src/lib.rs:1998:13

---- tests::move_post_should_work stdout ----
thread 'tests::move_post_should_work' panicked at 'Expected Ok(_). Got Err(
    DispatchError::Module {
        index: 0,
        error: 0,
        message: Some(
            "AccountIsBlocked",
        ),
    },
)', pallets/df-integration-tests/src/lib.rs:1919:13

---- tests::move_hidden_post_should_work stdout ----
thread 'tests::move_hidden_post_should_work' panicked at 'Expected Ok(_). Got Err(
    DispatchError::Module {
        index: 0,
        error: 0,
        message: Some(
            "AccountIsBlocked",
        ),
    },
)', pallets/df-integration-tests/src/lib.rs:1955:13


failures:
    tests::move_hidden_post_should_fail_cannot_move_comment
    tests::move_hidden_post_should_fail_no_permission_to_create_post
    tests::move_hidden_post_should_work
    tests::move_post_should_work

test result: FAILED. 136 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out
```

2021-03-24 16:15 UTC, F3Joule commented
> 4 failures in df-integration-tests:

Fixed already

2021-03-31 17:46 UTC, subsocialdev requested changes

2021-04-17 15:40 UTC, merged